### PR TITLE
Fix post ticket notes

### PR DESCRIPTION
**Pull request by vdechenaux**
Hi,

This PR fixes the POST of ticket notes.
According to the doc, the endpoint is `notes` http://developer.freshdesk.com/api/#add_note_to_a_ticket
I tested it, and it works (I have a 404 without the fix)

### CODE REVIEW

**Comment by mpclarkson** [comment]
Wonderful. Thanks for this PR. We don't use notes so I didn't pick it up.

**Comment by vdechenaux** [comment]
What do you think about a `0.2.6` tag?
Thanks!

**Comment by mpclarkson** [comment]
Done 👍

**Comment by vdechenaux** [comment]
:+1: Thanks a lot!

**Pull request merged**
